version: 2

sources:
  - name: raw
    schema: raw_data_circle
    tables:
      - name: parcel
        identifier: raw_cc_parcel
        description: info about order shipments
        columns:
          - name: Parcel_id
            description: id of the parcel
            tests:
              - not_null
              - unique
      - name: product
        identifier: raw_cc_parcel_product
        description: product list inside the parcel
        columns:
          - name: ParCEL_id
            tests:
              - not_null

models:
  - name: stg_parcel
    columns:
      - name: parcel_id
        tests:
          - not_null